version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: frontier-ctf-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=frontier-ctf
    networks:
      - frontier-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: frontier-ctf-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/frontier-ctf
      - JWT_SECRET=a17468a3faaeb4af5ebfc3befdda4a4d7f81417acff21c296cc7a2ca5ed6476717d45a386956a1689fe8beb9990cd98df5f69019f24ad101736ae6bf011f4505
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - frontier-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontier-ctf-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - frontier-network

volumes:
  mongodb_data:

networks:
  frontier-network:
    driver: bridge

